config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'dpo', to: 'pages#dpo'
  get 'pricing', to: 'pages#pricing'
  get 'smartcontract', to: 'pages#smartcontract'
  get 'justice', to: 'pages#justice'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dpo
  end

  def pricing
  end

  def smartcontract
  end

  def justice
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Law For Tech</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag "smartcontracts.png"%>

    <% if Rails.env.production? %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-135367356-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-135367356-1');
      </script>
    <% end %>
  </head>


  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dpo.html.erb
<div class="dpo-banner">
  <div class="banner-content text-center">
    <h1>Data Protection Officer as a Service</h1>
    <h2>Hands-On Privacy Expertise When You Need It</h2>
  </div>
</div> <!-- dpo banner -->

<div class="container dpo-offer">
	<div class="row">
		<div class="col-md-offset-4 col-md-4 col-xs-12">
			<div class="pain">
				<h3 class="card-pain text-center">
					Pain
				</h3>
			</div>
		</div>
		<div class="col-md-offset-1 col-md-10 col-xs-12">
			<p>
				Hiring a DPO is a pain for companies. The DPO has a <b>senior function</b> within the company but cannot be picked from its top management (CEO, CTO, etc.) to guarantee independence.</p><p>This usually means hiring externally. But DPOs are <b>expensive (and busy)</b> people.<p>Plus, there are not that many DPOs that combine <b>legal expertise</b> and <b>tech ability</b>.</p>
			</p>
		</div>
	</div> <!-- .row -->
	<div class="pricing">
		<div class="row">
			<div class="col-md-offset-4 col-md-4">
				<div class="solution">
					<h3 class="card-solution text-center">
						Solution
					</h3>
				</div>
			</div>
		</div> <!-- .row -->
		<div class="row">
			<div class="col-md-offset-1 col-md-10 col-xs-12">
				<p>Designate a Data Protection Officer for your company and benefit from:</p>
				<p>
					<ul>
					<li><b>10 hours assistance</b> from a <%= link_to "CIPP/E certified", "https://drive.google.com/file/d/1Bjb93q5LqmpOWuFoqV3b5JKE2BGt2ylJ/view?usp=sharing", target: "_blank" %> DPO when you need it most</li>
					<li><b>24/7 hotline</b> assistance on personal data breach notifications</li>
					<li><b>Registration</b> at the competent data protection authority</li>
					<li><b>Tick the "DPO" box once and for all</b> (and share the news with your investors, employees and customers).</li>
					</ul>
				</p> 
			</div>
		</div>
		<div class="row">
			<div class="col-md-offset-4 col-md-4 col-xs-12">
				<div class="card-pricing text-center">
					<h3>
						€ 950/year <span>(excl. VAT)</span>
					</h3>
					<p>
						€ 95 (billed monthly) <span>(excl. VAT)</span>
					</p>
					<div class="btn-get-started"><%= link_to "GET STARTED", "https://avdbranden.typeform.com/to/B50TIV", target: "_blank", class: "btn btn-primary btn-lg frame-btn" %>
					</div>
				</div>
			</div>
		</div> <!-- .row -->
	</div> <!-- .pricing --> 
</div> <!-- .container -->

app/views/pages/home.html.erb
<!-- Main banner-->

<div class="main-banner">
  <div class="banner-content text-center">
    <h1>Law For Tech</h1>
    <h2>Taking Legal out of the Way<br>of Tech Companies</h2>
   	<%= link_to "WHAT IS YOUR BIGGEST LEGAL HEADACHE?", "https://avdbranden.typeform.com/to/B50TIV", target: "_blank", class: "btn btn-primary btn-lg frame-btn" %>
  </div> <!-- .row -->
</div> <!-- .container -->

<!-- Presentation -->

<div class="container text-center nutshell">
	<div class="row">
		<h1>Adrien in a nutshell</h1>
  </div> <!-- .row -->
</div> <!-- .container -->

<div class="container presentation">
  <div class="row">
    <div class="col-md-offset-1 col-md-3 col-xs-12">
      <div class="volet-picture">
        <%= image_tag "adrien.jpg", class: "img-responsive img-adrien" %>
      </div>
    </div>
    <div class="col-md-7 col-xs-12">
      <div class="adrien-bio">
        <p>Hello world!</p>
        <p>My name is Adrien and if you are a tech professional, I would be happy cracking down on your legal woes. <b>My mission it to take legal out of your way</b> so you can focus on what matters most to you: growing your business.</p>
        <p>In a nutshell, I read the law at the University of Louvain (both at the French-and Dutch-speaking institutions) and at the University of Cambridge (where I obtained a post-grad in commercial law).</p>
        <p>I earned my stripes as a business lawyer in international law firms <%= link_to "Linklaters", "https://www.linklaters.com/en", target: "_blank"%> and <%= link_to "CMS", "https://cms.law/en/INT/", target: "_blank"%>, mainly dealing with intellectual property and data protection matters. Most and foremost, I learned coding at <%= link_to "Le Wagon", "https://www.lewagon.com/", target: "_blank"%> school, which makes me a kind of a rare breed in the legal sector. <b>I crafted this website myself</b> using Ruby as main programming language (with the help of the Rails framework). You can see (and contribute to) the source code on this GitHub public <%= link_to "repository", "https://github.com/avdbranden/lawfortech", target: "_blank"%>.</p>
        <p>What's more? I am a <%= link_to "certified privacy professional", "https://drive.google.com/file/d/1Bjb93q5LqmpOWuFoqV3b5JKE2BGt2ylJ/view?usp=sharing", target: "_blank" %> and lawyer recommended by the <%= link_to "Legal 500", "https://www.legal500.com/firms/557-cms/10156-brussels-belgium", target: "_blank" %> directory in the Telecoms & IT sector. I work in English, French and Dutch. For more info, see my full profile on <%= link_to "LinkedIn", "https://www.linkedin.com/in/adrienvandenbranden/", target: "_blank"%> or have a glimpse at <%= link_to "my CV", "https://drive.google.com/file/d/1trHlc2_Pnn8JptWqHkxtuakbMGfT3GYU/view?usp=sharing", target: "_blank"%> (the old-fashioned way).</p>
        </div>
      </div>
  </div> <!-- .row -->
 </div> <!-- .container -->

 <div class="container lined-middle-gray lined-middle-gray-1"></div>

 <div class="container text-center">
 	<div class="row">
 		<div class="col-xs-12">
 			<h2 class="integrate">Adrien integrates seamlessly into your favourite apps!</h2>
 		</div>
  </div> <!-- .row -->
 </div><!-- .container -->

<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-1 col-xs-6">
      <div class="int">
        <div class="int-title">
          <p>GMail</p>
        </div>
        <div class="int-logo">
          <%= image_tag "gmail.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
    <div class="col-md-1 col-xs-6">
      <div class="int">
        <div class="int-title">
          <p>GDrive</p>
        </div>
        <div class="int-logo">
          <%= image_tag "gdrive.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
    <div class="col-md-1 col-xs-6">
      <div class="int">
        <div class="int-title">
          <p>Trello</p>
        </div>
        <div class="int-logo">
          <%= image_tag "trello.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
    <div class="col-md-1 col-xs-6">
      <div class="int">
        <div class="int-title">
          <p>Github</p>
        </div>
        <div class="int-logo">
          <%= image_tag "github.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
    <div class="col-md-1 col-xs-6">
      <div class="int">
        <div class="int-title">
          <p>Dropbox</p>
        </div>
        <div class="int-logo">
          <%= image_tag "dropbox.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
    <div class="col-md-1 col-xs-6">
      <div class="int">
        <div class="int-title">
          <p>Slack</p>
        </div>
        <div class="int-logo">
          <%= image_tag "slack.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
    <div class="col-md-1 col-xs-6">
      <div class="int">
        <div class="int-title">
          <p>Calendar</p>
        </div>
        <div class="int-logo">
          <%= image_tag "googlecalendar.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
    <div class="col-md-1 col-xs-6">
      <div class="int">
        <div class="int-title">
          <p>Evernote</p>
        </div>
        <div class="int-logo">
          <%= image_tag "evernote.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
  </div> <!-- .row -->
 </div> <!-- .container -->

<div class="background-stuff">
	 <div class="container">
		<div class="row">
			<h1 class="stuff text-center">Stuff I can help your business with</h1>
		</div>
		<div class="row">
			<div class="col-md-offset-1 col-md-10 col-xs-12">
			    <p>
			      I can assist your business in navigating the <b>European and Belgian legal landscape</b> in matters such as data protection, information security, intellectual property and general commercial stuff.
			  	</p>
			  	<p>
			      If you're looking for examples of what I've done, please spare a sight for the list below:
			 	</p>
			 		<ul>
  			 			<li>Assisting a global car manufacturer in the launch of their <b>connected cars</b> throughout Europe</li>
  			 			<li>Implementing the <b>General Data Protection Regulation</b> (GDPR) for 30+ companies and charities of all shapes and sizes in Belgium and Europe</li>
  			 			<li>Assessing the severity of countless <b>personal data breaches</b> and notifying them to the competent data protection authorities and/or the affected data subjects</li>
  			 			<li>Preparing the <b>information security policies</b> in view of obtaining ISO/IEC 27001:2013 certification</li>
  			 			<li>Drafting <b>complex licensing agreements</b> involving <b>open source</b> software and licensing exceptions.</li>
	  				</ul>
	    		</p>
	    	</div>
  </div> <!-- .row -->
 </div> <!-- .container -->
</div> <!-- .background-stuff -->

<div class="secondary-banner">
  <div class="banner-content text-center">
    <h1>Want Legal Solved at Your Business?</h1>
    <p>Drop me a line at <b><%= link_to "adrien@lawfortech.io", "mailto:adrien@lawfortech.io"%> </b></p>
    <p>Or if you prefer specifying your needs, click on the "hire me" button below</p>
    <div class="btn-hire-me"><%= link_to "HIRE ME", "https://avdbranden.typeform.com/to/B50TIV", target: "_blank", class: "btn btn-primary btn-lg frame-btn" %></div>
  </div>
</div>

app/views/pages/justice.html.erb
<div class="container heading-title text-center">
	<div class="row">
		<div class="col-xs-12">
			<h1>Digital Justice</h1>
		</div>
	</div>
</div>

 <div class="container lined-middle-gray lined-middle-gray-1"></div> 

 <div class="container">
  	<div class="row">
    	<div class="col-md-6 col-xs-12">
      		<div class="book-pres">
      			<h4 class="book-titles">Justice Is Falling Short of Expectations</h4>
		    	   <p>Hav you noticed how technology impacts every sector of society but justice?</p>
           		<p>There is <b>a wide gap</b> between <b>how justice is provided</b> to ordinary citizens and <b>their legitimate expectations</b>. Citizens are used to benefit from a service that is online, of a good quality, fast and affordable. Justice seems at odds with those features. Justice evolves in a paper world, is slow, expensive and quality is not always optimal.</p>
            	<p>What can be done about it? This is the question I ask in my essay "Les robots à l'assaut de la justice". In this book, I argue that the way forward is to foster a <b>more efficient justice</b> i.e. a service offering a better ratio value-money-speed.</p>
            	<h4 class="book-titles">How to Make the Courts More Efficient?</h4>
		        <p>Order the book to find out.</p>
		        <p>You can buy it here or at your regular bookstore (the book is in French).</p>
		        <div class="text-center">
		        	<%= link_to "ORDER THE BOOK", "https://www.larcier.com/fr/les-robots-a-l-assaut-de-la-justice-2019-9782802763222.html", target: "_blank", class: "btn btn-primary btn-lg frame-btn btn-book" %>	
		        </div>
            <p>Ideas on how to build a more efficient justice?</p>
            <p>Share them by clicking on the button below or drop me an email at <%= link_to "adrien@lawfortech.io", "mailto:adrien@lawfortech.io" %>.</p>
            <div class="text-center">
              <div class="btn-get-started"><%= link_to "CONTRIBUTE", "https://avdbranden.typeform.com/to/B50TIV", target: "_blank", class: "btn btn-success btn-lg btn-book" %>
              </div>
            </div>
    		</div>
   		 </div>
   		 	<div class="col-md-6 col-xs-12">
   		   		<div class="book-picture">
   		    		<%= image_tag "roasju.jpg", class: "img-responsive" %>
   		   		</div>
   		 	</div>
  	</div> <!-- .row -->
</div> <!-- .container -->

app/views/pages/pricing.html.erb
<div class="container heading-title text-center">
	<div class="row">
		<div class="col-xs-12">
			<h1>Pricing</h1>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="lined-middle-gray">
		</div>
	</div>
</div>


<div class="container pricing-context">
	<div class="row">
		<div class="col-md-offset-1 col-md-10 col-xs-12">
			<p>
				When I visit the "Our Fee" section of a business law firm, I find it hilarious how lawyers manage to stress the importance of transparency of their fees while <b>providing absolutely no hard figures</b>. This lack of transparency is not unique to the legal sector but it is certainly exacerbating the tensions between lawyers' and clients' expectations.
			</p>
			<p>
				To me though, <b>transparency is key</b>. 1) It allows you, the potential client, to have at least a ballpark idea of <b>how much you will pay</b> for my services (you will see that I try to standardise most of my work). 2) It allows me not to waste time on quoting cheap clients who just want to compare prices (working for such clients leaves me cold). Publicy displaying my rates might be risky (since "this is not an industry standard" and "lawyers woud never do that") but I am confident that doing so will <b>attract the right kind of clients</b> who value openness and efficiency.
			</p>
			<p>
				Without further ado, here is what you can expect when hiring me for the following deliverables (note that fees are excluding VAT). 
			</p>
		</div>
	</div>
</div>

<div class="container pricing-table">
	<div class="row">
		<div class="col-md-offset-2 col-md-8 col-xs-12">
			<table class="table table-bordered table-hover">
			  <thead class="table-pricing-header">
			    <tr>
			      <th scope="col">Deliverable</th>
			      <th scope="col">Pricing</th>
			      <th scope="col">Extra Info</th>
			    </tr>
			  </thead>
			  <tbody class="table-pricing-body">
			    <tr>
			      <td>Privacy Policy (for charities)</td>
			      <td><b class="free">*FREE*</b></td>
			      <td>Less money spent on legal stuff means more money spent on charitable goals</td>
			    </tr>
			    <tr>
			      <td>Privacy Policy (for consumers)</td>
			      <td><b>€ 300</b></td>
			      <td>€ 150 for each of an additional English, French or Dutch version</td>
			    </tr>
			    <tr>
			      <td>Privacy Policy (for employees)</td>
			      <td><b>€ 400</b></td>
			      <td>€ 200 for each of an additional English, French or Dutch version</td>
			    </tr>
			    <tr>
			      <td>Privacy Policy (in the healthcare sector)</td>
			      <td><b>€ 600</b></td>
			      <td>€ 250 for each of an additional English, French or Dutch version</td>
			    </tr>
			    <tr>
			      <td>Cookies Usage Policy</td>
			      <td><b>€ 300</b></td>
			      <td>€ 150 for each of an additional English, French or Dutch version</td>
			    </tr>
			    <tr>
			      <td>Records of processing activities (art. 30 GDPR)</td>
			      <td><b>€ 850</b></td>
			      <td>In English, including a short procedure to maintain the records</td>
			    </tr>
			    <tr>
			      <td>Template data processing agreement/addendum (controller-friendly)</td>
			      <td><b>€ 450</b></td>
			      <td>€ 200 for each of an additional English, French or Dutch version</td>
			    </tr>
			    <tr>
			      <td>Template data processing agreement/addendum (processor-friendly)</td>
			      <td><b>€ 600</b></td>
			      <td>€ 250 for each of an additional English, French or Dutch version</td>
			    </tr>
			  </tbody>
			</table>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="lined-middle-gray">
		</div>
	</div>
</div>

<div class="container text-center pricing-end">
	<div class="row">
		<div class="col-md-offset-1 col-md-10 col-xs-12">
			<p>
				For specific projects, I will prepare a <b>fee quote</b> based on the below rates (excluding VAT). Note that I will try most of the time to work on the basis of a forfait.
			</p>
		</div>
	</div> <!-- .row -->
	<div class="row">
		<div class="col-md-offset-4 col-md-4 col-xs-12">	
			<table class="table table-bordered table-hover table-rate">
			  <thead class="table-pricing-header">
			    <tr">
			      <th scope="col">Timing</th>
			      <th scope="col">Rate</th>
			    </tr>
			  </thead>
			  <tbody class="table-pricing-body">
			    <tr>
			      <td>Hourly rate</td>
			      <td><b>€ 165</b></td>
			    </tr>
			    <tr>
			      <td>Man-day rate</td>
			      <td><b>€ 950</b></td>
			    </tr>
			  </tbody>
			</table>
		</div>
	</div> <!-- .row -->
	<div class="row">
		<div class="col-md-offset-1 col-md-10 col-xs-12">
			<p>For longer projects, I will <b>adapt my man-day rate</b> so that it remains manageable at your end. I will always try to find the arrangement that best suits your expectations.
			</p>
			<p>Still sounding good so far? Excellent! </p>
			<p>Get started today! Click on the button below or drop me an email at <%= link_to "adrien@lawfortech.io", "mailto:adrien@lawfortech.io" %>.</p>
			<div class="btn-get-started"><%= link_to "GET STARTED", "https://avdbranden.typeform.com/to/B50TIV", target: "_blank", class: "btn btn-primary btn-lg frame-btn" %>
			</div>
		</div>
	</div> <!-- .row -->
</div> <!--. container -->

app/views/pages/smartcontract.html.erb
<div class="container text-center heading-title">
	<div class="row">
		<h1>Smart Contracts</h1>
	</div>
</div>

 <div class="container lined-middle-gray lined-middle-gray-1"></div> 

 <div class="container sc-presentation">
  	<div class="row">
    	<div class="col-md-offset-1 col-md-3 col-xs-12">
      		<div class="volet-picture">
       		<%= image_tag "smartcontracts.png", class: "img-responsive img-ethereum" %>
      		</div> 
    	</div>
    	<div class="col-md-7 col-xs-12">
      		<div class="adrien-bio">
		        <p>A Smart Contract is a "contract" that is "smart" because it is both <b>documenting</b> and <b>executing</b> the terms of an agreement between parties.</p>
            <p>I am teaching lawyers how to design and sign their first Smart Contract on the <%= link_to "Ethereum", "https://en.wikipedia.org/wiki/Ethereum", target: "_blank" %> blockchain (you can see the Ethereum logo on the picture on the left). I do this in the context of the <%= link_to "Law Is Code", "https://lawiscode.io", target: "_blank" %> initiative which I set up with a software engineer (and friend).</p>
            <p>Smart Contracts (and more broadly blockchain) is a field of study in which I am currently <b>investing a lot of my time</b>.</p>
		        <p>If everything goes to plan, I will soon be able to provide clients with <b>slick home-made Smart Contracts</b>. I don't think clients will accept the bulky value chain where they first ask a lawyer to draft a plain-English contract and then ask an engineer to translate it into a Smart Contract. Bettet have one tech-enabled lawyer  do the job once and right from the start.</p>
		        <p>Stay tuned for more exciting news from the Smart Contracts universe!</p>	
    		</div>
   		 </div>
  	</div> <!-- .row -->
</div> <!-- .container -->

app/views/shared/_footer.html.erb
<div class="container footer lined-middle-gray text-center">
  <div class="row">
    <div class="col-md-2 col-xs-12 footer-copyright"> 
        <h4>Contact via:</h4> 
    </div>
    <div class="col-md-1 col-xs-12 footer-copyright">
       <%= link_to "mailto:adrien@lawfortech.io" do %>
         <%= image_tag "contactemail.png", size: "50",class: "img-rounded" %>
       <% end %>   
    </div>
    <div class="col-md-1 col-xs-12 footer-copyright">
       <%= link_to "https://www.linkedin.com/in/adrienvandenbranden/", target: "_blank" do %>
         <%= image_tag "linkedinbtn.png", size: "50",class: "img-rounded" %>
       <% end %>   
    </div>
    <div class="col-md-1 col-xs-12 text footer-copyright">
       <%= link_to "https://github.com/avdbranden", target: "_blank" do %>
         <%= image_tag "github.png", size: "50",class: "img-rounded" %>
       <% end %>  
    </div>
    <div class="col-md-1 col-xs-12 footer-copyright">
      <%= link_to "https://www.meetup.com/members/190649489/", target: "_blank" do %>
        <%= image_tag "meetup.png", size: "50",class: "img-rounded" %>
      <% end %> 
    </div>
    <div class="col-md-1 col-xs-12 footer-copyright">
       <%= link_to "https://medium.com/@avdbranden", target: "_blank" do %>
         <%= image_tag "medium.png", size: "50",class: "img-rounded" %>
       <% end %> 
    </div>
    <div class="col-md-3 col-xs-12 footer-copyright"> 
        <h4>Law For Tech</h4> 
    </div>
    <div class="col-md-2 col-xs-12 footer-copyright"> 
        <h4>© <%= Date.today.year %></h4> 
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav role="navigation" class="navbar navbar-default navbar-fixed-top bg-faded">
    <div class="navbar-conf">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to root_path do %>
                  <%= image_tag "smartcontracts.png", class: "img-rounded img-responsive" %>
                <% end %>
            </div>
            <!-- Collection of nav links and other content for toggling -->
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Data Protection Officer", dpo_path %></li>
                    <li><%= link_to "Digital Justice", justice_path %></li>
                    <li><%= link_to "Smart Contracts", smartcontract_path %></li>
                    <li><%= link_to "Law Is Code", "https://lawiscode.io", target: "_blank" %></li>
                    <li><%= link_to "Reshape.legal", "http://www.reshape.legal", target: "_blank" %></li>
                </ul>
            </div>
        </div>
    </div>
</nav>